### PR TITLE
bump version number on docs.

### PR DESCRIPTION
**Pull request by schettino72**

### CODE REVIEW

**Comment by asvetlov** [comment]
Would you calculate library version like `aiohttp` does: https://github.com/KeepSafe/aiohttp/blob/master/docs/conf.py#L21-L33 ?

**Comment by schettino72** [comment]
too busy lately. i will take a look next weekend...

**Comment by schettino72** [comment]
ok. now version is taken from `__init__.py`

**Comment by asvetlov** [comment]
Thanks

**Pull request merged**
